import type { Config } from "../../src/config/inputs.js";

export const baseConfig: Config = {
  anthropicApiKey: "x",
  claudeCodeOAuthToken: "",
  githubApp: { clientId: "id", privateKey: "key" },
  reviewGithubApp: null,
  sshSigningKey: null,
  triggerLabel: null,
  maxReviewIterations: 3,
  triageModel: "claude-sonnet-4-6",
  specModel: "claude-opus-4-7[1m]",
  planModel: "claude-opus-4-7[1m]",
  implModel: "claude-opus-4-7[1m]",
  reviewModels: {
    compliance: "claude-opus-4-7[1m]",
    bugs: "claude-opus-4-7[1m]",
    security: "claude-opus-4-7[1m]",
    smells: "claude-opus-4-7[1m]",
  },
  triageEffort: "high",
  specEffort: "high",
  planEffort: "high",
  implEffort: "high",
  reviewEfforts: {
    compliance: "high",
    bugs: "high",
    security: "high",
    smells: "high",
  },
  triageMaxBudgetUsd: 0.25,
  specMaxBudgetUsd: 1.5,
  planMaxBudgetUsd: 1.5,
  implMaxBudgetUsd: 2.5,
  reviewMaxBudgetUsdPerLens: 0.75,
  triageMaxTurns: undefined,
  specMaxTurns: undefined,
  planMaxTurns: undefined,
  implMaxTurns: undefined,
  reviewMaxTurnsPerLens: undefined,
  triageTimeoutMs: 60_000,
  specTimeoutMs: 120_000,
  planTimeoutMs: 120_000,
  implTimeoutMs: 360_000,
  reviewTimeoutMsPerLens: 90_000,
  mode: "auto" as const,
  stages: [] as Array<"triage" | "spec" | "plan" | "implement" | "review">,
};
