name: Shopfloor on Shopfloor
on:
  issues:
    types: [opened, edited, closed, labeled, unlabeled]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize, closed, labeled, unlabeled, ready_for_review]
  pull_request_review:
    types: [submitted]

jobs:
  shopfloor:
    uses: ./.github/workflows/shopfloor.yml
    permissions:
      contents: write
      pull-requests: read
      issues: read
      id-token: write
      actions: read
      statuses: read
      checks: read
    secrets: inherit
    with:
      trigger_label: "shopfloor:trigger"
